Repository ironcore-dev/gardener-extension-provider-ironcore-metal, pull requests merged in 2025-02, with the labels that each got.

#120 Bump `k8s.io/*` deps to v0.32 and `gardener` to v1.110
  .github/workflows/lint.yml
  Makefile
  example/20-crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  example/20-crd-druid.gardener.cloud_etcds.yaml
  example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/20-crd-extensions.gardener.cloud_backupentries.yaml
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/20-crd-extensions.gardener.cloud_clusters.yaml
  example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/20-crd-extensions.gardener.cloud_extensions.yaml
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  example/20-crd-extensions.gardener.cloud_networks.yaml
  example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  example/20-crd-resources.gardener.cloud_managedresources.yaml
  go.mod
  go.sum
  hack/api-reference/api.md
  hack/api-reference/config.md
  pkg/admission/validator/webhook.go
  pkg/controller/controlplane/suite_test.go
  pkg/controller/infrastructure/infrastructure_suite_test.go
  pkg/controller/worker/suite_test.go
Labels: documentation, enhancement, controllers, size/L

#140 Fix `BGPFilters` chart fmt
  charts/internal/shoot-system-components/charts/calico-bgp/templates/bgpfilter.yaml
  charts/internal/shoot-system-components/charts/calico-bgp/templates/bgppeer.yaml
Labels: bug, size/XS

#146 `BGPFilter` helm resource name equals to API config
  charts/internal/shoot-system-components/charts/calico-bgp/templates/bgpfilter.yaml
Labels: bug, size/XS

#151 Skip GH release for Helm chart
  .github/workflows/release-chart.yml
Labels: size/XS, chore
