Repository ironcore-dev/gardener-extension-provider-ironcore-metal, pull requests merged in 2025-06, with the labels that each got.

#194 Add tagged Helm charts release
  .github/workflows/release-chart.yml
Labels: size/M, chore

#191 Update `gardener/gardener` to `v1.118.0`
  charts/gardener-extension-provider-ironcore-metal/templates/deployment.yaml
  charts/gardener-extension-provider-ironcore-metal/values.yaml
  cmd/gardener-extension-admission-metal/app/app.go
  cmd/gardener-extension-provider-metal/app/app.go
  example/20-crd-extensions.gardener.cloud_workers.yaml
  example/controller-registration.yaml
  go.mod
  go.sum
  pkg/controller/worker/add.go
Labels: enhancement, controllers, size/L

#198 Fix chart version in publishing workflow
  .github/workflows/release-chart.yml
Labels: bug, size/S, chore

#207 Extend `NodeNamePolicy` to support `BMCName`
  pkg/apis/metal/types_controlplane.go
  pkg/apis/metal/v1alpha1/types_controlplane.go
  pkg/webhook/controlplane/ensurer.go
Labels: enhancement, size/S, api-change, area/metal-automation
